services:
  fileuploaderapi.server:
    image: ${DOCKER_REGISTRY-}fileuploaderapiserver
    container_name: fileuploaderapi.server
    build:
      context: .
      dockerfile: FileUploaderAPI.Server/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - FileService:BaseUrl=http://file.service:5002/api/files/
  file.service:
    image: ${DOCKER_REGISTRY-}fileservice
    container_name: file.service
    build:
      context: FileService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      - "5003:5003"
  runtrackr-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: runtrackr.blob-storage
    volumes:
      - ./.cotainers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
  client:
    image: client-ui
    build:
      context: ./fileuploaderapi.client
      dockerfile: ./Dockerfile
    ports:
      - 4000:80 
  notification.service:
    image: ${DOCKER_REGISTRY-}notificationservice
    container_name: notification.service
    build:
      context: NotificationService
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
