services:
  fileuploaderapi.server:
    image: ${DOCKER_REGISTRY-}fileuploaderapiserver
    container_name: fileuploaderapi.server
    build:
      context: .
      dockerfile: FileUploaderAPI.Server/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - FileService:BaseUrl=http://file.service:5002/api/files/

  file.service:
    image: ${DOCKER_REGISTRY-}fileservice
    container_name: file.service
    build:
      context: FileService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      - "5003:5003"
    environment:
      - NotificationService:BaseUrl=http://notification.service:5004/
      - ConnectionStrings:BlobStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite-blob-storage:10000/devstoreaccount1;
  
  azurite-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite.blob-storage
    volumes:
      - ./.cotainers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

  client:
    image: client-ui
    container_name: client
    build:
      context: ./fileuploaderapi.client
      dockerfile: ./Dockerfile
    ports:
      - 4000:80 

  notification.service:
    image: ${DOCKER_REGISTRY-}notificationservice
    container_name: notification.service
    build:
      context: NotificationService
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
      - "5005:5005"