services:
  fileuploaderapi.server:
    image: ${DOCKER_REGISTRY-}fileuploaderapiserver
    container_name: fileuploaderapi.server
    build:
      context: .
      dockerfile: FileUploaderAPI.Server/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  client:
    image: client-ui
    build:
      context: ./fileuploaderapi.client
      dockerfile: ./Dockerfile
    ports:
      - 4000:80 
