version: '3.9'

services:
  file-service:
    build:
      context: ../FileService
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BlobStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://blob-storage:10000/devstoreaccount1;
      - BlobStorage__ContainerName=uploads
    depends_on:
      - blob-storage
      - notification-service

  notification-service:
    build:
      context: ../NotificationService
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  api-gateway:
    build:
      context: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - file-service
      - notification-service

  client:
    build:
      context: ../fileuploaderapi.client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=development

  blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"  # Blob service (default port)
    volumes:
      - ./data/blob:/data
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==